# Generated by Django 6.0.3 on 2026-05-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatmessage',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aichatmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='aichatmessage',
            index=models.Index(fields=['status'], name='ai_coaching_status_d770d4_idx'),
        ),
    ]
