# Generated by Django 6.0.3 on 2026-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationsession',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='user',
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='order_index',
            field=models.PositiveIntegerField(),
        ),
    ]
