# Generated by Django 6.0.3 on 2026-04-14 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversationsession_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('emotion', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('annoyed', 'Annoyed'), ('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('mixed', 'Mixed'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('casual', 'Casual'), ('polite', 'Polite'), ('cold', 'Cold'), ('sensitive', 'Sensitive'), ('aggressive', 'Aggressive'), ('awkward', 'Awkward'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('strategy', models.TextField(blank=True)),
                ('recommended_replies', models.JSONField(blank=True, default=list)),
                ('caution_points', models.JSONField(blank=True, default=list)),
                ('follow_up_suggestions', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('source_type', models.CharField(choices=[('electron', 'Electron'), ('web', 'Web'), ('api', 'API'), ('other', 'Other')], default='electron', max_length=20)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('gemini_extract_raw', models.JSONField(blank=True, null=True)),
                ('gemini_analyze_raw', models.JSONField(blank=True, null=True)),
                ('screen_context', models.JSONField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('content', models.TextField()),
                ('message_order', models.PositiveIntegerField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['message_order', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='session',
        ),
        migrations.AlterModelOptions(
            name='conversationsession',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='situation_type',
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='conversation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='platform_type',
            field=models.CharField(choices=[('kakao', 'KakaoTalk'), ('instagram', 'Instagram'), ('sms', 'SMS'), ('discord', 'Discord'), ('whatsapp', 'WhatsApp'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='goal_type',
            field=models.CharField(choices=[('keep_good', 'Keep Good Relationship'), ('build_interest', 'Build Interest'), ('resolve_conflict', 'Resolve Conflict'), ('persuade', 'Persuade'), ('distance', 'Keep Distance'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='relation_type',
            field=models.CharField(choices=[('friend', 'Friend'), ('crush', 'Crush'), ('partner', 'Partner'), ('family', 'Family'), ('boss', 'Boss'), ('coworker', 'Coworker'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', 'status'], name='conversatio_user_id_17db32_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', 'platform_type'], name='conversatio_user_id_3f7266_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['conversation_key'], name='conversatio_convers_068753_idx'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='conversations.conversationsession'),
        ),
        migrations.AddField(
            model_name='capturerequest',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='conversations.conversationsession'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='capture_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='conversations.capturerequest'),
        ),
        migrations.AddField(
            model_name='extractedmessage',
            name='capture_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_messages', to='conversations.capturerequest'),
        ),
        migrations.AddField(
            model_name='extractedmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_messages', to='conversations.conversationsession'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddIndex(
            model_name='capturerequest',
            index=models.Index(fields=['session', 'processing_status'], name='conversatio_session_48ad6b_idx'),
        ),
        migrations.AddIndex(
            model_name='capturerequest',
            index=models.Index(fields=['uploaded_at'], name='conversatio_uploade_aaa65f_idx'),
        ),
        migrations.AddIndex(
            model_name='capturerequest',
            index=models.Index(fields=['detected_at'], name='conversatio_detecte_639067_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['session', 'created_at'], name='conversatio_session_3a50d2_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['capture_request'], name='conversatio_capture_376181_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['risk_level'], name='conversatio_risk_le_1f7275_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedmessage',
            index=models.Index(fields=['capture_request', 'message_order'], name='conversatio_capture_764497_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedmessage',
            index=models.Index(fields=['session'], name='conversatio_session_2683bd_idx'),
        ),
    ]
