# Generated by Django 6.0.3 on 2026-04-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_analysisresult_capturerequest_extractedmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturerequest',
            name='image_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='capturerequest',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='captures/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='analysis_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='relationship_context',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='capturerequest',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
