# Generated by Django 6.0.3 on 2026-05-09 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_capturerequest_image_base64_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='situation_context',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation_type', models.CharField(choices=[('friend', 'Friend'), ('crush', 'Crush'), ('partner', 'Partner'), ('family', 'Family'), ('boss', 'Boss'), ('coworker', 'Coworker'), ('other', 'Other')], default='other', max_length=20)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('personality', models.TextField(blank=True)),
                ('speech_style', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='conversations.avatar'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['user', 'is_active'], name='conversatio_user_id_e7faa4_idx'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['user', 'relation_type'], name='conversatio_user_id_e41f41_idx'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['user', 'name'], name='conversatio_user_id_c77b10_idx'),
        ),
    ]
