# Generated by Django 6.0.3 on 2026-05-09 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversationsession_situation_context_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='age_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='avatar',
            name='current_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='avatar',
            name='target_relation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['user', 'current_relation'], name='conversatio_user_id_2223e0_idx'),
        ),
    ]
