# Generated by Django 6.0.3 on 2026-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturerequest',
            name='image_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='capturerequest',
            index=models.Index(fields=['session', 'image_hash'], name='conversatio_session_f9d73f_idx'),
        ),
    ]
